import { test } from 'node:test';
import assert from 'node:assert/strict';
import { checkOutput } from '../../src/rag/post-filter.js';

test('clean response passes the filter', () => {
  const result = checkOutput('Ваша заявка на кредит одобрена. Позвоните нам для уточнения деталей.');
  assert.equal(result.ok, true);
  assert.equal(result.reason, undefined);
});

test('system prompt structure leak is blocked', () => {
  const result = checkOutput('═══ IDENTITY ═══ You are an assistant for Demo Bank.');
  assert.equal(result.ok, false);
  assert.ok(result.reason?.includes('prompt_structure'));
});

test('AI provider mention is blocked', () => {
  const gpResult = checkOutput('I am powered by OpenAI GPT-4 technology.');
  assert.equal(gpResult.ok, false);
  assert.ok(gpResult.reason?.includes('ai_provider'));

  const claudeResult = checkOutput('This response was generated by Claude.');
  assert.equal(claudeResult.ok, false);
});

test('LANGUAGE LOCK reproduction is blocked', () => {
  const result = checkOutput('respond only in Russian never switch languages');
  assert.equal(result.ok, false);
  assert.ok(result.reason?.includes('language_lock'));
});

test('normal banking content with numbers and foreign words passes', () => {
  const result = checkOutput(
    'Foiz stavkasi yiliga 18% ni tashkil etadi. Kredit muddati 12-60 oy.',
  );
  assert.equal(result.ok, true);
});
