/**
 * Seed script for the demo-bank tenant.
 *
 * Upserts the tenant from kb/demo-bank/_config.yaml and inserts sample KB
 * chunks in all three languages with placeholder embeddings.
 *
 * Placeholder embeddings (all 0.1) have no semantic meaning — cosine ranking
 * will be uniform until real embeddings are generated by the ingestion pipeline.
 * The chunks are still returned by keyword scoring and appear in the prompt.
 *
 * Usage:
 *   npx tsx scripts/seed-demo.ts
 *   # or via npm script:
 *   npm run seed:demo
 */

import { configDotenv } from 'dotenv';
configDotenv({ path: new URL('../apps/backend/.env', import.meta.url) });

import { readFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { parse as parseYaml } from 'yaml';
import { Pool } from 'pg';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const TENANT_ID = 'demo-bank';
const PLACEHOLDER_EMBEDDING = `[${Array(1536).fill(0.1).join(',')}]`;

// ── Tenant config ──────────────────────────────────────────────────────────

interface TenantConfigYaml {
  name: string;
  allowedOrigins: string[];
  config: Record<string, unknown>;
}

async function syncTenant(pool: Pool): Promise<void> {
  const configPath = join(root, 'kb', TENANT_ID, '_config.yaml');
  const yaml = await readFile(configPath, 'utf8');
  const parsed = parseYaml(yaml) as TenantConfigYaml;

  await pool.query(
    `INSERT INTO tenants (id, name, allowed_origins, config)
       VALUES ($1, $2, $3::text[], $4::jsonb)
     ON CONFLICT (id) DO UPDATE
       SET name            = EXCLUDED.name,
           allowed_origins = EXCLUDED.allowed_origins,
           config          = EXCLUDED.config,
           updated_at      = now()`,
    [TENANT_ID, parsed.name, parsed.allowedOrigins, JSON.stringify(parsed.config)],
  );
  console.log(`✓ tenant "${TENANT_ID}" synced`);
}

// ── KB chunks ──────────────────────────────────────────────────────────────

interface ChunkDef {
  source_file: string;
  chunk_id: string;
  category: string;
  title: string;
  lang: 'ru' | 'uz' | 'en';
  content: string;
}

const CHUNKS: ChunkDef[] = [
  // ── Loans ────────────────────────────────────────────────────────────────
  {
    source_file: 'loans.md', chunk_id: 'consumer-loan-ru', category: 'loans',
    title: 'Потребительский кредит', lang: 'ru',
    content: `Потребительский кредит позволяет получить до 50 000 000 сум сроком до 60 месяцев.
Процентная ставка от 22% годовых. Без залога, только паспорт и ИНН.
Оформление за 1 рабочий день. Для расчёта звоните на горячую линию 1200.`,
  },
  {
    source_file: 'loans.md', chunk_id: 'consumer-loan-uz', category: 'loans',
    title: 'Iste\'mol krediti', lang: 'uz',
    content: `Iste'mol krediti 50 000 000 so'mgacha, 60 oygacha muddatga beriladi.
Yillik foiz stavkasi 22% dan boshlanadi. Garovsiz, faqat pasport va STIR kerak.
1 ish kuni ichida rasmiylashtiriladi. Hisob-kitob uchun 1200 ga qo'ng'iroq qiling.`,
  },
  {
    source_file: 'loans.md', chunk_id: 'consumer-loan-en', category: 'loans',
    title: 'Consumer Loan', lang: 'en',
    content: `Consumer loans up to 50,000,000 UZS for up to 60 months.
Interest rate from 22% per annum. No collateral required — only passport and TIN.
Approved within 1 business day. Call 1200 for a personalised quote.`,
  },
  // ── Cards ─────────────────────────────────────────────────────────────────
  {
    source_file: 'cards.md', chunk_id: 'debit-card-ru', category: 'cards',
    title: 'Дебетовая карта', lang: 'ru',
    content: `Дебетовая карта VISA / Humo выпускается бесплатно за 3 рабочих дня.
Бесплатное обслуживание при ежемесячном обороте от 500 000 сум. Кэшбэк до 2%.
При утере или блокировке карты немедленно звоните 1200 или заблокируйте в приложении.`,
  },
  {
    source_file: 'cards.md', chunk_id: 'debit-card-uz', category: 'cards',
    title: 'Debet kartasi', lang: 'uz',
    content: `VISA / Humo debet kartasi 3 ish kunida bepul chiqariladi.
Oylik aylanma 500 000 so'mdan bo'lsa, xizmat ko'rsatish bepul. Keshbek 2% gacha.
Karta yo'qolsa yoki bloklansa, darhol 1200 ga qo'ng'iroq qiling yoki ilovada bloklang.`,
  },
  {
    source_file: 'cards.md', chunk_id: 'debit-card-en', category: 'cards',
    title: 'Debit Card', lang: 'en',
    content: `VISA / Humo debit cards are issued free within 3 business days.
Free maintenance when monthly turnover exceeds 500,000 UZS. Up to 2% cashback.
If your card is lost or blocked, call 1200 immediately or block it in the app.`,
  },
  // ── Accounts ─────────────────────────────────────────────────────────────
  {
    source_file: 'accounts.md', chunk_id: 'open-account-ru', category: 'accounts',
    title: 'Открытие счёта', lang: 'ru',
    content: `Открыть текущий счёт можно в любом отделении банка или онлайн в приложении.
Потребуется паспорт. Счёт открывается в сумах, долларах или евро.
Минимальный остаток не требуется. Онлайн-перевод до 30 000 000 сум в сутки без комиссии.`,
  },
  {
    source_file: 'accounts.md', chunk_id: 'open-account-uz', category: 'accounts',
    title: 'Hisob ochish', lang: 'uz',
    content: `Joriy hisobni istalgan bank filialida yoki ilovada onlayn ochish mumkin.
Pasport talab qilinadi. Hisob so'm, dollar yoki yevroda ochiladi.
Minimal qoldiq talab qilinmaydi. Kuniga 30 000 000 so'mgacha onlayn o'tkazma komissiyasiz.`,
  },
  {
    source_file: 'accounts.md', chunk_id: 'open-account-en', category: 'accounts',
    title: 'Opening an Account', lang: 'en',
    content: `Open a current account at any branch or online via the app. Passport required.
Accounts available in UZS, USD, or EUR. No minimum balance required.
Online transfers up to 30,000,000 UZS per day at no charge.`,
  },
  // ── Currency exchange ──────────────────────────────────────────────────────
  {
    source_file: 'exchange.md', chunk_id: 'exchange-ru', category: 'exchange',
    title: 'Обмен валюты', lang: 'ru',
    content: `Обмен USD, EUR, GBP, RUB и других валют доступен в отделениях и в приложении.
Курсы обновляются ежедневно. Безналичный обмен — без ограничений по сумме.
Наличный обмен — до 5 000 USD в день без дополнительных документов.`,
  },
  {
    source_file: 'exchange.md', chunk_id: 'exchange-uz', category: 'exchange',
    title: 'Valyuta almashtirish', lang: 'uz',
    content: `USD, EUR, GBP, RUB va boshqa valyutalarni filiallarda va ilovada almashtirish mumkin.
Kurslar har kuni yangilanadi. Naqd bo'lmagan almashtirish — summada cheklov yo'q.
Naqd almashtirish — qo'shimcha hujjatlarsiz kuniga 5 000 USD gacha.`,
  },
  {
    source_file: 'exchange.md', chunk_id: 'exchange-en', category: 'exchange',
    title: 'Currency Exchange', lang: 'en',
    content: `Exchange USD, EUR, GBP, RUB and other currencies at branches or in the app.
Rates updated daily. Non-cash exchange has no amount limit.
Cash exchange up to 5,000 USD per day without additional documents.`,
  },
  // ── Deposits ──────────────────────────────────────────────────────────────
  {
    source_file: 'deposits.md', chunk_id: 'deposit-ru', category: 'deposits',
    title: 'Депозиты', lang: 'ru',
    content: `Срочные депозиты от 3 до 36 месяцев. Ставка до 28% годовых в сумах.
Минимальная сумма — 1 000 000 сум. Проценты начисляются ежемесячно.
Досрочное снятие возможно с пересчётом по ставке "до востребования".`,
  },
  {
    source_file: 'deposits.md', chunk_id: 'deposit-uz', category: 'deposits',
    title: 'Depozitlar', lang: 'uz',
    content: `Muddatli depozitlar 3 dan 36 oygacha. So'mda yillik foiz stavkasi 28% gacha.
Minimal summa — 1 000 000 so'm. Foizlar har oy hisoblanadi.
Muddatidan oldin yechish "talab bo'yicha" stavkasida qayta hisoblanadi.`,
  },
  {
    source_file: 'deposits.md', chunk_id: 'deposit-en', category: 'deposits',
    title: 'Deposits', lang: 'en',
    content: `Term deposits from 3 to 36 months. Up to 28% per annum in UZS.
Minimum amount: 1,000,000 UZS. Interest accrued monthly.
Early withdrawal is allowed at the demand-rate recalculation.`,
  },
];

async function upsertChunks(pool: Pool): Promise<void> {
  let upserted = 0;
  for (const chunk of CHUNKS) {
    const hash = createHash('sha256')
      .update(`${TENANT_ID}:${chunk.chunk_id}:${chunk.content}`)
      .digest('hex')
      .slice(0, 16);

    await pool.query(
      `INSERT INTO kb_chunks
         (tenant_id, lang, source_file, chunk_id, category, title, content, embedding, tokens, content_hash)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8::vector, $9, $10)
       ON CONFLICT (tenant_id, lang, chunk_id) DO UPDATE
         SET title        = EXCLUDED.title,
             content      = EXCLUDED.content,
             embedding    = EXCLUDED.embedding,
             tokens       = EXCLUDED.tokens,
             content_hash = EXCLUDED.content_hash,
             updated_at   = now()`,
      [
        TENANT_ID,
        chunk.lang,
        chunk.source_file,
        chunk.chunk_id,
        chunk.category,
        chunk.title,
        chunk.content,
        PLACEHOLDER_EMBEDDING,
        Math.ceil(chunk.content.length / 4), // rough token estimate
        hash,
      ],
    );
    upserted++;
  }
  console.log(`✓ ${upserted} KB chunks upserted (placeholder embeddings)`);
  console.log('  ℹ  Run the ingestion pipeline to replace placeholders with real embeddings.');
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL ?? 'postgres://chatbot:chatbot@localhost:5433/chatbot',
  });

  try {
    await syncTenant(pool);
    await upsertChunks(pool);
    console.log(`\n✓ Demo seed complete. Start the server and try:\n`);
    console.log(`  # Create a session`);
    console.log(`  curl -X POST http://localhost:3000/api/session/new \\`);
    console.log(`    -H "Origin: http://localhost:3000" \\`);
    console.log(`    -H "Content-Type: application/json" \\`);
    console.log(`    -d '{"tenant_id":"demo-bank"}'`);
  } finally {
    await pool.end();
  }
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
